# Generated by Django 3.2.4 on 2021-07-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': 'Shool',
                'verbose_name_plural': 'Shools',
            },
        ),
    ]
