# Generated by Django 3.2.4 on 2021-06-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolhouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shool',
            old_name='City',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shool',
            old_name='adress',
            new_name='city',
        ),
    ]
