# Generated by Django 3.2.4 on 2021-07-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(upload_to='course/files'),
        ),
    ]
