# Generated by Django 3.2.4 on 2021-11-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_alter_lesson_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(null=True, upload_to='course/files'),
        ),
    ]
